spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assina?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: assinaadmin
    password: assinaadmin

  level:
    org:
      springframework:
        security: TRACE

  jpa:
    show-sql: true
    hibernate:
      # TODO replace this with ddl files
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
